import type { Metadata } from "next";
import "./globals.css";
import { GameOfSquids } from "@/lib/font";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
    title: "AAKAR 2025 | Brains, Guts and Glory",
    description:
        "Experience the spirit of innovation, creativity, and competition at AAKAR 2025 – a premier TechnoCultural fest bringing together students, tech enthusiasts, and innovators for exciting events, workshops, and unforgettable memories.",
    keywords: [
        "AAKAR 2025","TechnoCultural Fest","Engineering Fest","Cultural Fest India","Student Innovation","Workshops","Competitions","Technical Events","Cultural Events",
        "College Fest","Best College Fest in India","AAKAR Events","AAKAR Tech Fest","AAKAR Cultural Night","AAKAR Workshops","AAKAR Competitions","College Fest Karnataka",
        "South India Tech Fest","Student Techno Fest","Youth Cultural Fest","Tech Symposium 2025","Hackathon India","Robotics Competition","Technical Paper Presentation",
        "Dance Battle College","Music Fest for Students","Innovation Challenge","Entrepreneurship Event","Cultural Talent Hunt","Online Gaming Competition","LAN Gaming Fest",
        "Web Development Event","Python Workshop College","AI ML Workshop","Drone Making College Event","App Development Challenge","Battle of Bands India","DJ Night College",
        "Street Play Competition","Fashion Show College Fest","Photography Contest College","Short Film Competition","Youth Festival India","Top College Fests India",
        "AAKAR Registration 2025","Techno Fest Schedule","College Tech Fest Winners","Coding Contest 2025","Innovation Hackathon","Startup Pitch Fest","UI UX Design Contest",
        "Google Developer Fest","Fest for Coders","Fest for Designers","AAKAR Official Website","AAKAR Registration Link","AAKAR Tumkur","AAKAR AIT College","Karnataka College Fest",
        "Top Fests for Engineers","Engineering Student Fest","College Fest Ideas","Fests with Huge Prize Pools","Cultural Events 2025","Best Workshops 2025","Innovative College Fests",
        "Tech + Culture Festival","Youth Empowerment Events","College Drama Contest","Idea Presentation Competition","National Level Fest","All India College Fest","Music Production Workshop",
        "Spoken Word Event","Open Mic Night","Quiz Bowl College","Treasure Hunt College Event","Gaming Night","Live Coding Contest","Animation Workshop Students","Digital Art College Event",
        "Meme Making Contest","Green Innovation Challenge","Science Exhibition College","College Robotics Show","Data Science Bootcamp","Machine Learning Basics","Tech Trivia Quiz",
        "Python Coding Fest","Blockchain Student Workshop","Campus Tech Revolution","Tech Fest India 2025","Trophy Night College","Fest Closing Ceremony","College Event Photos",
        "AAKAR 2025 Aftermovie","Register for AAKAR","Plan your trip AAKAR","Best Events AAKAR","AAKAR 2025 Highlights","AAKAR 2025 official fest","AAKAR Techno-Cultural Fest",
        "AAKAR engineering college fest","AAKAR Tumkur fest","AAKAR AIT College event","AAKAR national level fest","AAKAR best college fest Karnataka","AAKAR fest registration 2025",
        "AAKAR fest dates","AAKAR fest schedule","AAKAR fest highlights","AAKAR fest aftermovie","AAKAR fest winners","AAKAR fest prize money","AAKAR fest sponsors","AAKAR fest guest speakers",
        "AAKAR fest chief guest","AAKAR fest theme","AAKAR fest logo","AAKAR fest Instagram","AAKAR hackathon 2025","AAKAR coding competition","AAKAR robotics challenge","AAKAR drone racing",
        "AAKAR AI/ML workshop","AAKAR Python programming contest","AAKAR web development battle","AAKAR app development challenge","AAKAR 2025","TechnoCultural Fest","Engineering Fest",
        "Cultural Fest India","Student Innovation","Workshops","Competitions","Technical Events","Cultural Events","College Fest","Best College Fest in India","AAKAR Events","AAKAR Tech Fest",
        "AAKAR Cultural Night","AAKAR Workshops","AAKAR Competitions","College Fest Karnataka","South India Tech Fest","Student Techno Fest","Youth Cultural Fest","Tech Symposium 2025",
        "Hackathon India","Robotics Competition","Technical Paper Presentation","Dance Battle College","Music Fest for Students","Innovation Challenge","Entrepreneurship Event","Cultural Talent Hunt",
        "Online Gaming Competition","LAN Gaming Fest","Web Development Event","Python Workshop College","AI ML Workshop","Drone Making College Event","App Development Challenge","Battle of Bands India",
        "DJ Night College","Street Play Competition","Fashion Show College Fest","Photography Contest College","Short Film Competition","Youth Festival India","Top College Fests India",
        "AAKAR Registration 2025","Techno Fest Schedule","College Tech Fest Winners","Coding Contest 2025","Innovation Hackathon","Startup Pitch Fest","UI UX Design Contest","Google Developer Fest",
        "Fest for Coders","Fest for Designers","AAKAR Official Website","AAKAR Registration Link","AAKAR Tumkur","AAKAR AIT College","Karnataka College Fest","Top Fests for Engineers",
        "Engineering Student Fest","College Fest Ideas","Fests with Huge Prize Pools","Cultural Events 2025","Best Workshops 2025","Innovative College Fests","Tech + Culture Festival",
        "Youth Empowerment Events","College Drama Contest","Idea Presentation Competition","National Level Fest","All India College Fest","Music Production Workshop","Spoken Word Event",
        "Open Mic Night","Quiz Bowl College","Treasure Hunt College Event","Gaming Night","Live Coding Contest","Animation Workshop Students","Digital Art College Event","Meme Making Contest",
        "Green Innovation Challenge","Science Exhibition College","College Robotics Show","Data Science Bootcamp","Machine Learning Basics","Tech Trivia Quiz","Python Coding Fest",
        "Blockchain Student Workshop","Campus Tech Revolution","Tech Fest India 2025","Trophy Night College","Fest Closing Ceremony","College Event Photos","AAKAR 2025 Aftermovie",
        "Register for AAKAR","Plan your trip AAKAR","Best Events AAKAR","AAKAR 2025 Highlights","AAKAR 2025 official fest","AAKAR Techno-Cultural Fest","AAKAR engineering college fest",
        "AAKAR Tumkur fest","AAKAR AIT College event","AAKAR national level fest","AAKAR best college fest Karnataka","AAKAR fest registration 2025","AAKAR fest dates","AAKAR fest schedule",
        "AAKAR fest highlights","AAKAR fest aftermovie","AAKAR fest winners","AAKAR fest prize money","AAKAR fest sponsors","AAKAR fest guest speakers","AAKAR fest chief guest","AAKAR fest theme",
        "AAKAR fest logo","AAKAR fest Instagram","AAKAR hackathon 2025","AAKAR coding competition","AAKAR robotics challenge","AAKAR drone racing","AAKAR AI/ML workshop","AAKAR Python programming contest",
        "AAKAR web development battle","AAKAR app development challenge","AAKAR 2025 fest","AAKAR annual fest","AAKAR mega event","AAKAR student fest","AAKAR biggest college fest","AAKAR tech and cultural fest",
        "AAKAR national fest","AAKAR inter-college fest","AAKAR tech symposium","AAKAR innovation summit","AAKAR startup expo","AAKAR tech exhibitions","AAKAR coding marathon","AAKAR AI challenge",
        "AAKAR robotics expo","AAKAR drone showcase","AAKAR cybersecurity workshop","AAKAR IoT competition","AAKAR AR/VR workshop","AAKAR cloud computing event","AAKAR data analytics contest",
        "AAKAR blockchain challenge","AAKAR ethical hacking workshop","AAKAR 3D printing contest","AAKAR electronics hackathon","AAKAR embedded systems event","AAKAR PCB design contest",
        "AAKAR circuit debugging","AAKAR tech quizzes","AAKAR engineering puzzles","AAKAR math olympiad","AAKAR physics challenge","AAKAR chemistry fest","AAKAR science fair","AAKAR tech debates",
        "AAKAR panel discussions","AAKAR leadership talks","AAKAR motivational speakers","AAKAR alumni meet","AAKAR industry connect","AAKAR career fair","AAKAR job expo","AAKAR tech recruitment",
        "AAKAR internship drive","AAKAR campus placements","AAKAR tech networking","AAKAR entrepreneurship summit","AAKAR pitch fest","AAKAR business plan competition","AAKAR startup funding",
        "AAKAR venture capital meet","AAKAR product launch","AAKAR tech demo day","AAKAR design sprint","AAKAR UI/UX hackathon","AAKAR graphic design contest","AAKAR digital marketing workshop",
        "AAKAR SEO challenge","AAKAR content writing contest","AAKAR blogging competition","AAKAR social media fest","AAKAR influencer meet","AAKAR photography workshop","AAKAR videography contest",
        "AAKAR filmmaking challenge","AAKAR short film fest","AAKAR documentary screening","AAKAR animation contest","AAKAR VFX workshop","AAKAR gaming tournament","AAKAR esports league",
        "AAKAR PUBG competition","AAKAR Free Fire contest","AAKAR Valorant tournament","AAKAR CS:GO championship","AAKAR FIFA gaming","AAKAR chess competition","AAKAR Rubik's cube contest",
        "AAKAR puzzle challenge","AAKAR escape room event","AAKAR treasure hunt","AAKAR scavenger hunt","AAKAR mystery challenge","AAKAR detective game","AAKAR coding treasure hunt",
        "AAKAR tech scavenger hunt","AAKAR robotics treasure hunt","AAKAR AI puzzle game","AAKAR machine learning challenge","AAKAR deep learning workshop","AAKAR NLP competition",
        "AAKAR computer vision contest","AAKAR big data challenge","AAKAR cloud challenge","AAKAR serverless computing","AAKAR quantum computing talk","AAKAR 5G technology workshop",
        "AAKAR 6G future tech","AAKAR space tech event","AAKAR satellite workshop","AAKAR astronomy fest","AAKAR astrophysics talk","AAKAR cosmology discussion","AAKAR science quiz",
        "AAKAR tech trivia","AAKAR engineering quiz","AAKAR math quiz","AAKAR physics quiz","AAKAR chemistry quiz","AAKAR biology fest","AAKAR medical tech expo","AAKAR healthcare innovation",
        "AAKAR biotech challenge","AAKAR genetic engineering","AAKAR bioinformatics workshop","AAKAR sustainable tech fest","AAKAR green energy challenge","AAKAR renewable energy workshop",
        "AAKAR solar power contest","AAKAR wind energy talk","AAKAR EV technology expo","AAKAR electric vehicle challenge","AAKAR battery tech workshop","AAKAR smart city challenge",
        "AAKAR IoT smart devices","AAKAR smart home contest","AAKAR automation challenge","AAKAR robotics automation","AAKAR industrial robotics","AAKAR humanoid robots","AAKAR drone tech expo",
        "AAKAR UAV competition","AAKAR drone photography","AAKAR aerial robotics","AAKAR autonomous drones","AAKAR AI drones","AAKAR quadcopter race","AAKAR FPV drone racing","AAKAR tech drone show",
        "AAKAR drone light show","AAKAR cultural performances","AAKAR dance competition","AAKAR classical dance","AAKAR western dance","AAKAR hip-hop battle","AAKAR breakdance contest","AAKAR contemporary dance",
        "AAKAR folk dance showcase","AAKAR Bollywood dance","AAKAR K-pop competition","AAKAR singing contest","AAKAR solo singing","AAKAR group singing","AAKAR acapella competition","AAKAR Indian classical music",
        "AAKAR western music fest","AAKAR rock band competition","AAKAR metal band contest","AAKAR fusion music","AAKAR instrumental fest","AAKAR guitar competition","AAKAR piano contest","AAKAR violin performance",
        "AAKAR flute recital","AAKAR tabla competition","AAKAR drum battle","AAKAR DJ competition","AAKAR EDM night","AAKAR trance music fest","AAKAR techno party","AAKAR live concert","AAKAR celebrity performance",
        "AAKAR stand-up comedy","AAKAR mimicry contest","AAKAR improv comedy","AAKAR roast battle","AAKAR poetry slam","AAKAR storytelling event","AAKAR debate competition","AAKAR elocution contest","AAKAR public speaking",
        "AAKAR motivational speaking","AAKAR TEDx-style talks","AAKAR panel debate","AAKAR youth parliament","AAKAR MUN competition","AAKAR drama fest","AAKAR theatre competition","AAKAR street play","AAKAR nukkad natak",
        "AAKAR mime performance","AAKAR mono acting","AAKAR skit competition","AAKAR short play","AAKAR Shakespeare fest","AAKAR modern theatre","AAKAR experimental drama","AAKAR fashion show","AAKAR runway competition",
        "AAKAR ethnic wear contest","AAKAR western wear show","AAKAR sustainable fashion","AAKAR upcycling challenge","AAKAR designer showcase","AAKAR modeling contest","AAKAR photography exhibition","AAKAR portrait contest",
        "AAKAR landscape photography","AAKAR macro photography","AAKAR wildlife photography","AAKAR street photography","AAKAR candid photography","AAKAR mobile photography","AAKAR DSLR workshop","AAKAR photo editing",
        "AAKAR Photoshop contest","AAKAR Lightroom workshop","AAKAR videography challenge","AAKAR short film making","AAKAR documentary contest","AAKAR vlogging competition","AAKAR YouTube fest","AAKAR reel making contest",
        "AAKAR meme fest","AAKAR digital art contest","AAKAR illustration challenge","AAKAR comic strip contest","AAKAR caricature competition","AAKAR anime drawing","AAKAR manga art fest","AAKAR 3D modeling contest",
        "AAKAR Blender workshop","AAKAR Maya animation","AAKAR VFX challenge","AAKAR game design contest","AAKAR Unity workshop","AAKAR Unreal Engine","AAKAR AR/VR gaming","AAKAR metaverse event","AAKAR NFT workshop",
        "AAKAR crypto challenge","AAKAR Web3 fest","AAKAR DeFi talk","AAKAR DAO discussion","AAKAR smart contracts","AAKAR Solidity workshop","AAKAR Ethereum challenge","AAKAR Polygon hackathon","AAKAR blockchain expo",
        "AAKAR fintech innovation","AAKAR edtech challenge","AAKAR agritech contest","AAKAR healthtech expo","AAKAR medtech workshop","AAKAR AI in healthcare","AAKAR robotics in medicine","AAKAR biotech innovation",
        "AAKAR genetic engineering","AAKAR synthetic biology","AAKAR space tech expo","AAKAR satellite design","AAKAR rocket science","AAKAR astronomy workshop","AAKAR astrophysics quiz","AAKAR cosmology talk",
        "AAKAR quantum physics","AAKAR string theory","AAKAR science fiction fest","AAKAR sci-fi writing","AAKAR futuristic tech","AAKAR innovation showcase","AAKAR student projects","AAKAR research expo",
        "AAKAR thesis presentation","AAKAR paper publication","AAKAR academic fest","AAKAR knowledge summit","AAKAR tech conference","AAKAR engineering expo","AAKAR science congress","AAKAR research symposium",
        "AAKAR PhD colloquium","AAKAR academic workshop","AAKAR faculty meet","AAKAR industry-academia","AAKAR corporate connect","AAKAR startup incubator","AAKAR innovation lab","AAKAR maker space","AAKAR tinkering lab",
        "AAKAR prototyping contest","AAKAR product design","AAKAR industrial design","AAKAR ergonomics workshop","AAKAR human factors","AAKAR UX research","AAKAR UI design sprint","AAKAR Figma challenge",
        "AAKAR Adobe XD contest","AAKAR Sketch workshop","AAKAR wireframing contest","AAKAR prototyping challenge","AAKAR design thinking","AAKAR ideation workshop","AAKAR brainstorming session","AAKAR problem-solving",
        "AAKAR case study competition","AAKAR business challenge","AAKAR market research","AAKAR customer analysis","AAKAR sales pitch","AAKAR negotiation contest","AAKAR leadership challenge","AAKAR team building",
        "AAKAR management fest","AAKAR HR workshop","AAKAR talent acquisition","AAKAR recruitment drive","AAKAR resume building","AAKAR interview prep","AAKAR career counseling","AAKAR personality development","AAKAR soft skills",
        "AAKAR communication workshop","AAKAR body language","AAKAR public speaking","AAKAR confidence building","AAKAR stress management","AAKAR time management","AAKAR productivity workshop","AAKAR mindfulness session",
        "AAKAR meditation workshop","AAKAR yoga fest","AAKAR wellness challenge","AAKAR fitness competition","AAKAR sports fest","AAKAR cricket tournament","AAKAR football match","AAKAR basketball contest","AAKAR volleyball competition",
        "AAKAR badminton championship","AAKAR table tennis","AAKAR athletics meet","AAKAR marathon run","AAKAR cycling race","AAKAR swimming competition","AAKAR kabaddi tournament","AAKAR kho-kho contest","AAKAR wrestling match",
        "AAKAR martial arts demo","AAKAR taekwondo contest","AAKAR karate championship","AAKAR judo competition","AAKAR boxing match","AAKAR MMA showcase","AAKAR adventure sports","AAKAR rock climbing","AAKAR trekking challenge",
        "AAKAR camping workshop","AAKAR survival skills","AAKAR outdoor leadership","AAKAR team adventure","AAKAR group challenge","AAKAR obstacle course","AAKAR ninja warrior","AAKAR parkour workshop","AAKAR freerunning contest",
        "AAKAR stunt performance","AAKAR acrobatics show","AAKAR gymnastics competition","AAKAR cheerleading contest","AAKAR dance crew battle","AAKAR flash mob event","AAKAR cultural parade","AAKAR heritage fest","AAKAR traditional arts",
        "AAKAR folk music","AAKAR classical arts","AAKAR handicraft exhibition","AAKAR pottery workshop","AAKAR painting contest","AAKAR sculpture making","AAKAR rangoli competition","AAKAR mehndi contest","AAKAR tattoo art","AAKAR calligraphy workshop",
        "AAKAR origami challenge","AAKAR paper craft","AAKAR DIY workshop","AAKAR upcycling contest","AAKAR recycling challenge","AAKAR sustainability fest","AAKAR eco-friendly products","AAKAR green campus","AAKAR zero waste","AAKAR climate action",
        "AAKAR environmental quiz","AAKAR wildlife conservation","AAKAR tree plantation","AAKAR clean energy","AAKAR solar workshop","AAKAR wind energy","AAKAR hydropower talk","AAKAR biofuel innovation","AAKAR electric vehicles","AAKAR EV workshop",
        "AAKAR battery tech","AAKAR charging stations","AAKAR smart grid","AAKAR energy efficiency","AAKAR carbon footprint","AAKAR climate tech","AAKAR clean tech","AAKAR future mobility","AAKAR smart transportation","AAKAR urban planning",
        "AAKAR smart cities","AAKAR IoT solutions","AAKAR AI for sustainability","AAKAR green architecture","AAKAR eco-design","AAKAR sustainable living","AAKAR organic farming","AAKAR hydroponics workshop","AAKAR vertical farming","AAKAR agri-tech expo",
        "AAKAR food innovation","AAKAR culinary contest","AAKAR cooking challenge","AAKAR baking competition","AAKAR mixology workshop","AAKAR mocktail contest","AAKAR food photography","AAKAR food blogging","AAKAR food tech","AAKAR nutrition workshop",
        "AAKAR health fest","AAKAR wellness expo","AAKAR mental health talk","AAKAR fitness challenge","AAKAR yoga competition","AAKAR Zumba workshop","AAKAR aerobics contest","AAKAR pilates session","AAKAR crossfit challenge","AAKAR weightlifting demo",
        "AAKAR bodybuilding contest","AAKAR powerlifting meet","AAKAR strongman competition","AAKAR functional fitness","AAKAR HIIT workout","AAKAR marathon training","AAKAR triathlon prep","AAKAR sports nutrition","AAKAR diet planning","AAKAR vegan cooking",
        "AAKAR plant-based diet","AAKAR superfoods talk","AAKAR immunity boosters","AAKAR Ayurveda workshop","AAKAR traditional medicine","AAKAR home remedies","AAKAR herbal medicine","AAKAR naturopathy talk","AAKAR acupuncture demo","AAKAR chiropractic session",
        "AAKAR physiotherapy workshop","AAKAR occupational therapy","AAKAR speech therapy","AAKAR cognitive training","AAKAR memory workshop","AAKAR speed reading","AAKAR learning techniques","AAKAR study hacks","AAKAR exam preparation","AAKAR competitive exams",
        "AAKAR entrance test prep","AAKAR scholarship info","AAKAR study abroad","AAKAR foreign education","AAKAR IELTS workshop","AAKAR TOEFL prep","AAKAR GRE coaching","AAKAR GMAT training","AAKAR SAT prep","AAKAR ACT workshop","AAKAR visa guidance",
        "AAKAR SOP writing","AAKAR LOR tips","AAKAR CV building","AAKAR interview skills","AAKAR group discussion","AAKAR case study prep","AAKAR aptitude test","AAKAR logical reasoning","AAKAR quantitative ability","AAKAR verbal ability",
        "AAKAR data interpretation","AAKAR coding aptitude","AAKAR technical interview","AAKAR HR interview","AAKAR mock interviews","AAKAR career guidance","AAKAR job search","AAKAR networking tips","AAKAR LinkedIn workshop",
        "AAKAR personal branding","AAKAR resume writing","AAKAR cover letter","AAKAR job application","AAKAR internship search","AAKAR freelancing guide","AAKAR startup funding","AAKAR venture capital","AAKAR angel investors",
        "AAKAR pitch deck","AAKAR business model","AAKAR lean startup","AAKAR MVP development","AAKAR product launch","AAKAR market research","AAKAR customer validation","AAKAR growth hacking","AAKAR digital marketing","AAKAR SEO workshop",
        "AAKAR social media marketing","AAKAR influencer marketing","AAKAR email marketing","AAKAR content marketing","AAKAR video marketing","AAKAR affiliate marketing","AAKAR Google Ads","AAKAR Facebook Ads","AAKAR Instagram marketing",
        "AAKAR YouTube marketing","AAKAR TikTok marketing","AAKAR Twitter marketing","AAKAR LinkedIn marketing","AAKAR Pinterest marketing","AAKAR Snapchat marketing","AAKAR Reddit marketing","AAKAR WhatsApp marketing","AAKAR Telegram marketing",
        "AAKAR Discord marketing","AAKAR community building","AAKAR forum marketing","AAKAR Quora marketing","AAKAR Medium blogging","AAKAR Substack newsletter","AAKAR podcasting workshop","AAKAR live streaming","AAKAR Twitch streaming",
        "AAKAR YouTube live","AAKAR Instagram live","AAKAR Facebook live","AAKAR Twitter spaces","AAKAR Clubhouse chat","AAKAR virtual events","AAKAR hybrid events","AAKAR metaverse events","AAKAR VR meetups","AAKAR AR experiences",
        "AAKAR 3D avatars","AAKAR NFT ticketing","AAKAR blockchain events","AAKAR DAO meetups","AAKAR Web3 conferences","AAKAR crypto workshops","AAKAR Bitcoin talk","AAKAR Ethereum discussion","AAKAR Solana workshop","AAKAR Polygon meetup",
        "AAKAR Avalanche talk","AAKAR Cardano event","AAKAR Polkadot workshop","AAKAR Cosmos meetup","AAKAR Algorand event","AAKAR Tezos workshop","AAKAR NFT art fest","AAKAR digital collectibles","AAKAR crypto gaming","AAKAR play-to-earn",
        "AAKAR GameFi workshop","AAKAR DeFi summit","AAKAR yield farming","AAKAR staking workshop","AAKAR liquidity mining","AAKAR DAO governance","AAKAR smart contracts","AAKAR Solidity coding","AAKAR Rust workshop","AAKAR Move language",
        "AAKAR Vyper coding","AAKAR Cairo workshop","AAKAR zero-knowledge proofs","AAKAR zk-SNARKs talk","AAKAR zk-STARKs workshop","AAKAR rollups discussion","AAKAR optimistic rollups","AAKAR ZK rollups","AAKAR sidechains talk",
        "AAKAR plasma chains","AAKAR state channels","AAKAR sharding workshop","AAKAR DAG technology","AAKAR hashgraph talk","AAKAR blockchain scaling","AAKAR layer 2 solutions","AAKAR interoperability","AAKAR cross-chain bridges",
        "AAKAR oracle networks","AAKAR Chainlink workshop","AAKAR API3 event","AAKAR Band Protocol","AAKAR decentralized identity","AAKAR DID workshop","AAKAR verifiable credentials","AAKAR soulbound tokens","AAKAR decentralized storage",
        "AAKAR IPFS workshop","AAKAR Filecoin event","AAKAR Arweave meetup","AAKAR Sia workshop","AAKAR Storj talk","AAKAR decentralized compute","AAKAR Akash Network","AAKAR Render Token","AAKAR Golem workshop","AAKAR AI compute",
        "AAKAR federated learning","AAKAR edge computing","AAKAR IoT blockchain","AAKAR smart cities","AAKAR 5G integration","AAKAR 6G future","AAKAR quantum computing","AAKAR post-quantum crypto","AAKAR homomorphic encryption",
        "AAKAR MPC workshop","AAKAR FHE discussion","AAKAR zero-trust security","AAKAR cybersecurity fest","AAKAR ethical hacking","AAKAR penetration testing","AAKAR bug bounty","AAKAR CTF competition","AAKAR red teaming","AAKAR blue teaming",
        "AAKAR purple teaming","AAKAR threat modeling","AAKAR risk assessment","AAKAR security audit","AAKAR smart contract audit","AAKAR blockchain forensics","AAKAR on-chain analysis","AAKAR crypto tracing","AAKAR AML compliance","AAKAR KYC solutions",
        "AAKAR privacy coins","AAKAR Monero workshop","AAKAR Zcash event","AAKAR Dash meetup","AAKAR Grin discussion","AAKAR Beam workshop","AAKAR Mimblewimble","AAKAR confidential assets","AAKAR ring signatures","AAKAR zk-proofs privacy",
        "AAKAR stealth addresses","AAKAR coin mixing","AAKAR decentralized VPN","AAKAR Tor network","AAKAR I2P workshop","AAKAR Freenet talk","AAKAR dark web","AAKAR deep web","AAKAR surface web","AAKAR internet privacy",
        "AAKAR data sovereignty","AAKAR GDPR compliance","AAKAR CCPA workshop","AAKAR HIPAA discussion","AAKAR SOC 2 audit","AAKAR ISO 27001","AAKAR NIST framework","AAKAR CIS controls","AAKAR OWASP top 10","AAKAR SANS top 20","AAKAR MITRE ATT&CK",
        "AAKAR cyber kill chain","AAKAR threat intelligence","AAKAR SIEM solutions","AAKAR SOAR platforms","AAKAR XDR workshop","AAKAR EDR solutions","AAKAR MDR services","AAKAR NDR talk","AAKAR deception tech","AAKAR honeypots workshop",
        "AAKAR canary tokens","AAKAR threat hunting","AAKAR incident response","AAKAR disaster recovery","AAKAR business continuity","AAKAR ransomware protection","AAKAR phishing defense","AAKAR social engineering","AAKAR vishing workshop",
        "AAKAR smishing talk","AAKAR pretexting demo","AAKAR baiting attack","AAKAR tailgating defense","AAKAR dumpster diving","AAKAR shoulder surfing","AAKAR USB drop attack","AAKAR evil twin demo","AAKAR man-in-the-middle","AAKAR session hijacking",
        "AAKAR DNS spoofing","AAKAR ARP poisoning","AAKAR BGP hijacking","AAKAR IP spoofing","AAKAR MAC flooding","AAKAR VLAN hopping","AAKAR STP attack","AAKAR DHCP starvation","AAKAR rogue AP attack","AAKAR WPS cracking","AAKAR WPA3 security",
        "AAKAR WPA2 vulnerabilities","AAKAR WEP cracking","AAKAR Bluetooth hacking","AAKAR NFC security","AAKAR RFID cloning","AAKAR contactless payment","AAKAR EMV chip security","AAKAR magstripe vulnerabilities","AAKAR ATM skimming","AAKAR POS malware",
        "AAKAR card-not-present fraud","AAKAR SIM swapping","AAKAR port-out scam","AAKAR call forwarding fraud","AAKAR PBX hacking","AAKAR voicemail hacking","AAKAR SS7 vulnerabilities","AAKAR Diameter protocol","AAKAR GTP security",
        "AAKAR SIP vulnerabilities","AAKAR RTP security","AAKAR WebRTC privacy","AAKAR STUN server","AAKAR TURN server","AAKAR ICE protocol","AAKAR NAT traversal","AAKAR firewall evasion","AAKAR IDS evasion","AAKAR IPS bypass",
        "AAKAR WAF bypass","AAKAR DDoS protection","AAKAR botnet mitigation","AAKAR IoT security","AAKAR OT security","AAKAR SCADA security","AAKAR ICS vulnerabilities","AAKAR PLC hacking","AAKAR RTU security","AAKAR HMI vulnerabilities",
        "AAKAR DCS security","AAKAR SIS workshop","AAKAR BMS security","AAKAR EMS vulnerabilities","AAKAR smart grid security","AAKAR smart meter hacking","AAKAR AMI security","AAKAR DER protection","AAKAR microgrid security","AAKAR vehicle cybersecurity",
        "AAKAR CAN bus hacking","AAKAR OBD2 vulnerabilities","AAKAR ECU security","AAKAR Tesla hacking","AAKAR connected car security","AAKAR autonomous vehicle","AAKAR V2X security","AAKAR drone cybersecurity","AAKAR UAV vulnerabilities",
        "AAKAR quadcopter hacking","AAKAR FPV security","AAKAR GPS spoofing","AAKAR GNSS vulnerabilities","AAKAR Galileo security","AAKAR GLONASS hacking","AAKAR BeiDou vulnerabilities","AAKAR IRNSS security","AAKAR QZSS hacking",
        "AAKAR satellite hacking","AAKAR space cybersecurity","AAKAR ISS vulnerabilities","AAKAR Starlink security","AAKAR OneWeb hacking","AAKAR Iridium vulnerabilities","AAKAR Inmarsat security","AAKAR VSAT hacking","AAKAR DVB vulnerabilities",
        "AAKAR DOCSIS security","AAKAR fiber hacking","AAKAR OTDR spoofing","AAKAR BGP security","AAKAR MPLS vulnerabilities","AAKAR SD-WAN security","AAKAR NFV hacking","AAKAR cloud security","AAKAR AWS security","AAKAR Azure vulnerabilities",
        "AAKAR GCP security","AAKAR OCI hacking","AAKAR Alibaba Cloud","AAKAR IBM Cloud","AAKAR Oracle Cloud","AAKAR VMware security","AAKAR Hyper-V vulnerabilities","AAKAR Xen security","AAKAR KVM hacking","AAKAR Docker security",
        "AAKAR Kubernetes vulnerabilities","AAKAR OpenShift security","AAKAR EKS hacking","AAKAR AKS vulnerabilities","AAKAR GKE security","AAKAR serverless security","AAKAR Lambda vulnerabilities","AAKAR Azure Functions","AAKAR Cloud Functions",
        "AAKAR FaaS security","AAKAR microservices vulnerabilities","AAKAR API security","AAKAR GraphQL security","AAKAR REST vulnerabilities","AAKAR SOAP security","AAKAR gRPC hacking","AAKAR WebSockets vulnerabilities","AAKAR Webhook security",
        "AAKAR OAuth vulnerabilities","AAKAR OpenID Connect","AAKAR SAML security","AAKAR JWT vulnerabilities","AAKAR session fixation","AAKAR CSRF protection","AAKAR XSS prevention","AAKAR SQL injection","AAKAR XXE vulnerabilities",
        "AAKAR SSRF protection","AAKAR LFI security","AAKAR RFI vulnerabilities","AAKAR RCE prevention","AAKAR deserialization vulnerabilities","AAKAR buffer overflow","AAKAR heap spraying","AAKAR ROP chain","AAKAR ASLR bypass","AAKAR DEP evasion",
        "AAKAR CFG protection","AAKAR sandbox escape","AAKAR VM escape","AAKAR container breakout","AAKAR kernel exploits","AAKAR privilege escalation","AAKAR lateral movement","AAKAR persistence techniques","AAKAR credential dumping","AAKAR pass-the-hash",
        "AAKAR golden ticket","AAKAR silver ticket","AAKAR kerberoasting","AAKAR AS-REP roasting","AAKAR DCSync attack","AAKAR NTLM relay","AAKAR LLMNR poisoning","AAKAR NetBIOS spoofing","AAKAR WPAD attack","AAKAR DNS poisoning","AAKAR DHCP spoofing",
        "AAKAR ARP spoofing","AAKAR STP attack","AAKAR VLAN hopping","AAKAR MAC flooding","AAKAR port security","AAKAR 802.1X bypass","AAKAR EAP vulnerabilities","AAKAR RADIUS security","AAKAR TACACS+ vulnerabilities","AAKAR LDAP security",
        "AAKAR Kerberos vulnerabilities","AAKAR NTLM security","AAKAR OAuth security","AAKAR OpenID vulnerabilities","AAKAR SAML security","AAKAR JWT vulnerabilities","AAKAR session fixation","AAKAR CSRF protection","AAKAR XSS prevention",
        "AAKAR SQL injection","AAKAR XXE vulnerabilities","AAKAR SSRF protection","AAKAR LFI security","AAKAR RFI vulnerabilities","AAKAR RCE prevention","AAKAR deserialization vulnerabilities","AAKAR buffer overflow","AAKAR heap spraying",
        "AAKAR ROP chain","AAKAR ASLR bypass","AAKAR DEP evasion","AAKAR CFG protection","AAKAR sandbox escape","AAKAR VM escape","AAKAR container breakout","AAKAR kernel exploits","AAKAR privilege escalation","AAKAR lateral movement",
        "AAKAR persistence techniques","AAKAR credential dumping","AAKAR pass-the-hash","AAKAR golden ticket","AAKAR silver ticket","AAKAR kerberoasting","AAKAR AS-REP roasting","AAKAR DCSync attack","AAKAR NTLM relay","AAKAR LLMNR poisoning",
        "AAKAR NetBIOS spoofing","AAKAR WPAD attack","AAKAR DNS poisoning","AAKAR DHCP spoofing","AAKAR ARP spoofing","AAKAR STP attack","AAKAR VLAN hopping","AAKAR MAC flooding","AAKAR port security","AAKAR 802.1X bypass","AAKAR EAP vulnerabilities",
        "AAKAR RADIUS security","AAKAR TACACS+ vulnerabilities","AAKAR LDAP security","AAKAR Kerberos vulnerabilities","AAKAR NTLM security","AAKAR OAuth security","AAKAR OpenID vulnerabilities","AAKAR SAML security","AAKAR JWT vulnerabilities",
        "AAKAR session fixation","AAKAR CSRF protection","AAKAR XSS prevention","AAKAR SQL injection","AAKAR XXE vulnerabilities","AAKAR SSRF protection","AAKAR LFI security","AAKAR RFI vulnerabilities","AAKAR RCE prevention",
        "AAKAR deserialization vulnerabilities","AAKAR buffer overflow","AAKAR heap spraying","AAKAR ROP chain","AAKAR ASLR bypass","AAKAR DEP evasion","AAKAR CFG protection","AAKAR sandbox escape","AAKAR VM escape","AAKAR container breakout",
        "AAKAR kernel exploits","AAKAR privilege escalation","AAKAR lateral movement","AAKAR persistence techniques","AAKAR credential dumping","AAKAR pass-the-hash","AAKAR golden ticket","AAKAR silver ticket","AAKAR kerberoasting",
        "AAKAR AS-REP roasting","AAKAR DCSync attack","AAKAR NTLM relay","AAKAR LLMNR poisoning","AAKAR NetBIOS spoofing","AAKAR WPAD attack","AAKAR DNS poisoning","AAKAR DHCP spoofing","AAKAR ARP spoofing","AAKAR STP attack",
        "AAKAR VLAN hopping","AAKAR MAC flooding","AAKAR port security","AAKAR 802.1X bypass","AAKAR EAP vulnerabilities","AAKAR RADIUS security","AAKAR TACACS+ vulnerabilities","AAKAR LDAP security","AAKAR Kerberos vulnerabilities",
        "AAKAR NTLM security","AAKAR OAuth security","AAKAR OpenID vulnerabilities","AAKAR SAML security","AAKAR JWT vulnerabilities","AAKAR session fixation","AAKAR CSRF protection","AAKAR XSS prevention","AAKAR SQL injection",
        "AAKAR XXE vulnerabilities","AAKAR SSRF protection","AAKAR LFI security","AAKAR RFI vulnerabilities","AAKAR RCE prevention","AAKAR deserialization vulnerabilities","AAKAR buffer overflow","AAKAR heap spraying","AAKAR ROP chain",
        "AAKAR ASLR bypass","AAKAR DEP evasion","AAKAR CFG protection","AAKAR sandbox escape","AAKAR VM escape","AAKAR container breakout","AAKAR kernel exploits","AAKAR privilege escalation","AAKAR lateral movement","AAKAR persistence techniques",
        "AAKAR credential dumping","AAKAR pass-the-hash","AAKAR golden ticket","AAKAR silver ticket","AAKAR kerberoasting","AAKAR AS-REP roasting","AAKAR DCSync attack","AAKAR NTLM relay","AAKAR LLMNR poisoning","AAKAR NetBIOS spoofing",
        "AAKAR WPAD attack","AAKAR DNS poisoning","AAKAR DHCP spoofing","AAKAR ARP spoofing","AAKAR STP attack","AAKAR VLAN hopping","AAKAR MAC flooding","AAKAR port security","AAKAR 802.1X bypass","AAKAR EAP vulnerabilities","AAKAR RADIUS security",
        "AAKAR TACACS+ vulnerabilities","AAKAR LDAP security","AAKAR Kerberos vulnerabilities","AAKAR NTLM security","AAKAR OAuth security","AAKAR OpenID vulnerabilities","AAKAR SAML security","AAKAR JWT vulnerabilities","AAKAR session fixation",
        "AAKAR CSRF protection","AAKAR XSS prevention","AAKAR SQL injection","AAKAR XXE vulnerabilities","AAKAR SSRF protection","AAKAR LFI security","AAKAR RFI vulnerabilities","AAKAR RCE prevention","AAKAR deserialization vulnerabilities",
        "AAKAR buffer overflow","AAKAR heap spraying","AAKAR ROP chain","AAKAR ASLR bypass","AAKAR DEP evasion","AAKAR CFG protection","AAKAR sandbox escape","AAKAR VM escape","AAKAR container breakout","AAKAR kernel exploits","AAKAR privilege escalation",
        "AAKAR lateral movement","AAKAR persistence techniques","AAKAR credential dumping","AAKAR pass-the-hash","AAKAR golden ticket","AAKAR silver ticket","AAKAR kerberoasting","AAKAR AS-REP roasting","AAKAR DCSync attack","AAKAR NTLM relay",
        "AAKAR LLMNR poisoning","AAKAR NetBIOS spoofing","AAKAR WPAD attack","AAKAR DNS poisoning","AAKAR DHCP spoofing","AAKAR ARP spoofing","AAKAR STP attack","AAKAR VLAN hopping","AAKAR MAC flooding","AAKAR port security","AAKAR 802.1X bypass",
        "AAKAR EAP vulnerabilities","AAKAR RADIUS security","AAKAR TACACS+ vulnerabilities","AAKAR LDAP security","AAKAR Kerberos vulnerabilities","AAKAR NTLM security","AAKAR OAuth security","AAKAR OpenID vulnerabilities","AAKAR SAML security",
        "AAKAR JWT vulnerabilities","AAKAR session fixation","AAKAR CSRF protection","AAKAR XSS prevention","AAKAR SQL injection","AAKAR XXE vulnerabilities","AAKAR SSRF protection","AAKAR LFI security","AAKAR RFI vulnerabilities","AAKAR RCE prevention",
        "AAKAR deserialization vulnerabilities","AAKAR buffer overflow","AAKAR heap spraying","AAKAR ROP chain","AAKAR ASLR bypass","AAKAR DEP evasion","AAKAR CFG protection","AAKAR sandbox escape","AAKAR VM escape","AAKAR container breakout",
        "AAKAR kernel exploits","AAKAR privilege escalation","AAKAR lateral movement","AAKAR persistence techniques","AAKAR credential dumping","AAKAR pass-the-hash","AAKAR golden ticket","AAKAR silver ticket","AAKAR kerberoasting","AAKAR AS-REP roasting",
        "AAKAR DCSync attack","AAKAR NTLM relay","AAKAR LLMNR poisoning","AAKAR NetBIOS spoofing","AAKAR WPAD attack","AAKAR DNS poisoning","AAKAR DHCP spoofing","AAKAR ARP spoofing","AAKAR STP attack","AAKAR VLAN hopping","AAKAR MAC flooding","AAKAR port security",
        "AAKAR 802.1X bypass","AAKAR EAP vulnerabilities","AAKAR RADIUS security","AAKAR TACACS+ vulnerabilities","AAKAR LDAP security","AAKAR Kerberos vulnerabilities","AAKAR NTLM security","AAKAR OAuth security","AAKAR OpenID vulnerabilities","AAKAR SAML security",
        "AAKAR JWT vulnerabilities","AAKAR session fixation","AAKAR CSRF protection","AAKAR XSS prevention","AAKAR SQL injection","AAKAR XXE vulnerabilities","AAKAR SSRF protection","AAKAR LFI security","AAKAR RFI vulnerabilities","AAKAR RCE prevention",
        "AAKAR deserialization vulnerabilities","AAKAR buffer overflow","AAKAR heap spraying","AAKAR ROP chain","AAKAR ASLR bypass","AAKAR DEP evasion","AAKAR CFG protection","AAKAR sandbox escape","AAKAR VM escape","AAKAR container breakout",
        "AAKAR kernel exploits","AAKAR privilege escalation","AAKAR lateral movement","AAKAR persistence techniques","AAKAR credential dumping","AAKAR pass-the-hash","AAKAR golden ticket","AAKAR silver ticket","AAKAR kerberoasting","AAKAR AS-REP roasting",
        "AAKAR DCSync attack","AAKAR NTLM relay","AAKAR LLMNR poisoning","AAKAR NetBIOS spoofing","AAKAR WPAD attack","AAKAR DNS poisoning","AAKAR DHCP spoofing","AAKAR ARP spoofing","AAKAR STP attack","AAKAR VLAN hopping","AAKAR MAC flooding","AAKAR port security",
        "AAKAR 802.1X bypass","AAKAR EAP vulnerabilities","AAKAR RADIUS security","AAKAR TACACS+ vulnerabilities","AAKAR LDAP security","AAKAR Kerberos vulnerabilities","AAKAR NTLM security","AAKAR OAuth security","AAKAR OpenID vulnerabilities","AAKAR SAML security",
        "AAKAR JWT vulnerabilities","AAKAR session fixation","AAKAR CSRF protection","AAKAR XSS prevention","AAKAR SQL injection","AAKAR XXE vulnerabilities","AAKAR SSRF protection","AAKAR LFI security","AAKAR RFI vulnerabilities","AAKAR RCE prevention",
        "AAKAR deserialization vulnerabilities","AAKAR buffer overflow","AAKAR heap spraying","AAKAR ROP chain","AAKAR ASLR bypass","AAKAR DEP evasion","AAKAR CFG protection","AAKAR sandbox escape","AAKAR VM escape","AAKAR container breakout","AAKAR kernel exploits",
        "AAKAR privilege escalation","AAKAR lateral movement","AAKAR persistence techniques","AAKAR credential dumping","AAKAR pass-the-hash","AAKAR golden ticket","AAKAR silver ticket","AAKAR kerberoasting","AAKAR AS-REP roasting","AAKAR DCSync attack","AAKAR NTLM relay",
        "AAKAR LLMNR poisoning","AAKAR NetBIOS spoofing","AAKAR WPAD attack","AAKAR DNS poisoning","AAKAR DHCP spoofing","AAKAR ARP spoofing","AAKAR STP attack","AAKAR VLAN hopping","AAKAR MAC flooding",
        "AAKAR port security","AAKAR 802.1X bypass","AAKAR EAP vulnerabilities","AAKAR RADIUS security","AAKAR TACACS+ vulnerabilities","AAKAR LDAP security","AAKAR Kerberos vulnerabilities","AAKAR NTLM security",
        "AAKAR OAuth security","AAKAR OpenID vulnerabilities","AAKAR SAML security","AAKAR JWT vulnerabilities","AAKAR session fixation","AAKAR CSRF protection","AAKAR XSS prevention","AAKAR SQL injection",
        "AAKAR XXE vulnerabilities","AAKAR SSRF protection","AAKAR LFI security","AAKAR RFI vulnerabilities","AAKAR RCE prevention","AAKAR deserialization vulnerabilities","AAKAR buffer overflow","AAKAR heap spraying",
        "AAKAR ROP chain","AAKAR ASLR bypass","AAKAR DEP evasion","AAKAR CFG protection","AAKAR sandbox escape","AAKAR VM escape","AAKAR container breakout","AAKAR kernel exploits","AAKAR privilege escalation",
        "AAKAR lateral movement","AAKAR persistence techniques","AAKAR credential dumping","AAKAR pass-the-hash","AAKAR golden ticket","AAKAR silver ticket","AAKAR kerberoasting","AAKAR AS-REP roasting","AAKAR DCSync attack",
        "AAKAR NTLM relay","AAKAR LLMNR poisoning","AAKAR NetBIOS spoofing","AAKAR WPAD attack","AAKAR DNS poisoning","AAKAR DHCP spoofing","AAKAR ARP spoofing","AAKAR STP attack","AAKAR VLAN hopping","AAKAR MAC flooding",
        "AAKAR port security","AAKAR 802.1X bypass","AAKAR EAP vulnerabilities","AAKAR RADIUS security","AAKAR TACACS+ vulnerabilities","AAKAR LDAP security","AAKAR Kerberos vulnerabilities","AAKAR NTLM security",
        "AAKAR OAuth security","AAKAR OpenID vulnerabilities","AAKAR SAML security","AAKAR JWT vulnerabilities","AAKAR session fixation","AAKAR CSRF protection","AAKAR XSS prevention","AAKAR SQL injection",
        "AAKAR XXE vulnerabilities","AAKAR SSRF protection","AAKAR LFI security","AAKAR RFI vulnerabilities","AAKAR RCE prevention","AAKAR deserialization vulnerabilities","AAKAR buffer overflow","AAKAR heap spraying",
        "AAKAR ROP chain","AAKAR ASLR bypass","AAKAR DEP evasion","AAKAR CFG protection","AAKAR sandbox escape","AAKAR VM escape","AAKAR container breakout","AAKAR kernel exploits","AAKAR privilege escalation",
        "AAKAR lateral movement","AAKAR persistence techniques","AAKAR credential dumping","AAKAR pass-the-hash","AAKAR golden ticket","AAKAR silver ticket","AAKAR kerberoasting","AAKAR AS-REP roasting","AAKAR DCSync attack",
        "AAKAR NTLM relay","AAKAR LLMNR poisoning","AAKAR NetBIOS spoofing","AAKAR WPAD attack","AAKAR DNS poisoning","AAKAR DHCP spoofing","AAKAR ARP spoofing","AAKAR STP attack","AAKAR VLAN hopping","AAKAR MAC flooding",
        "AAKAR port security","AAKAR 802.1X bypass","AAKAR EAP vulnerabilities","AAKAR RADIUS security","AAKAR TACACS+ vulnerabilities","AAKAR LDAP security","AAKAR Kerberos vulnerabilities","AAKAR NTLM security",
        "AAKAR OAuth security","AAKAR OpenID vulnerabilities","AAKAR SAML security","AAKAR JWT vulnerabilities","AAKAR session fixation","AAKAR CSRF protection","AAKAR XSS prevention","AAKAR SQL injection",
        "AAKAR XXE vulnerabilities","AAKAR SSRF protection","AAKAR LFI security","AAKAR RFI vulnerabilities","AAKAR RCE prevention","AAKAR deserialization vulnerabilities","AAKAR buffer overflow","AAKAR heap spraying",
        "AAKAR ROP chain","AAKAR ASLR bypass","AAKAR DEP evasion","AAKAR CFG protection","AAKAR sandbox escape","AAKAR VM escape","AAKAR container breakout","AAKAR kernel exploits","AAKAR privilege escalation",
        "AAKAR lateral movement","AAKAR persistence techniques","AAKAR credential dumping","AAKAR pass-the-hash","AAKAR golden ticket","AAKAR silver ticket","AAKAR kerberoasting","AAKAR AS-REP roasting","AAKAR DCSync attack",
        "AAKAR NTLM relay","AAKAR LLMNR poisoning","AAKAR NetBIOS spoofing","AAKAR WPAD attack","AAKAR DNS poisoning","AAKAR DHCP spoofing","AAKAR ARP spoofing","AAKAR STP attack","AAKAR VLAN hopping","AAKAR MAC flooding",
        "AAKAR port security","AAKAR 802.1X bypass","AAKAR EAP vulnerabilities","AAKAR RADIUS security","AAKAR TACACS+ vulnerabilities","AAKAR LDAP security","AAKAR Kerberos vulnerabilities","AAKAR NTLM security","AAKAR OAuth security",
        "AAKAR OpenID vulnerabilities","AAKAR SAML security","AAKAR JWT vulnerabilities","AAKAR session fixation","AAKAR CSRF protection","AAKAR XSS prevention","AAKAR SQL injection","AAKAR XXE vulnerabilities","AAKAR SSRF protection",
        "AAKAR LFI security","AAKAR RFI vulnerabilities","AAKAR RCE prevention","AAKAR deserialization vulnerabilities","AAKAR buffer overflow","AAKAR heap spraying","AAKAR ROP chain","AAKAR ASLR bypass","AAKAR DEP evasion",
        "AAKAR CFG protection","AAKAR sandbox escape","AAKAR VM escape","AAKAR container breakout","AAKAR kernel exploits","AAKAR privilege escalation","AAKAR lateral movement","AAKAR persistence techniques","AAKAR credential dumping",
        "AAKAR pass-the-hash","AAKAR golden ticket","AAKAR silver ticket","AAKAR kerberoasting","AAKAR AS-REP roasting","AAKAR DCSync attack","AAKAR NTLM relay","AAKAR LLMNR poisoning","AAKAR NetBIOS spoofing","AAKAR WPAD attack",
        "AAKAR DNS poisoning","AAKAR DHCP spoofing","AAKAR ARP spoofing","AAKAR STP attack","AAKAR VLAN hopping","AAKAR MAC flooding","AAKAR port security","AAKAR 802.1X bypass","AAKAR EAP vulnerabilities","AAKAR RADIUS security",
        "AAKAR TACACS+ vulnerabilities","AAKAR LDAP security","AAKAR Kerberos vulnerabilities","AAKAR NTLM security","AAKAR OAuth security","AAKAR OpenID vulnerabilities","AAKAR SAML security","AAKAR JWT vulnerabilities",
        "AAKAR session fixation","AAKAR CSRF protection","AAKAR XSS prevention","AAKAR SQL injection","AAKAR XXE vulnerabilities","AAKAR SSRF protection","AAKAR LFI security","AAKAR RFI vulnerabilities","AAKAR RCE prevention",
        "AAKAR deserialization vulnerabilities","AAKAR buffer overflow","AAKAR heap spraying","AAKAR ROP chain","AAKAR ASLR bypass","AAKAR DEP evasion","AAKAR CFG protection","AAKAR sandbox escape","AAKAR VM escape","AAKAR container breakout",
        "AAKAR kernel exploits","AAKAR privilege escalation","AAKAR lateral movement","AAKAR persistence techniques","AAKAR credential dumping","AAKAR pass-the-hash","AAKAR golden ticket","AAKAR silver ticket","AAKAR kerberoasting","AAKAR AS-REP roasting",
        "AAKAR DCSync attack","AAKAR NTLM relay","AAKAR LLMNR poisoning","AAKAR NetBIOS spoofing","AAKAR WPAD attack","AAKAR DNS poisoning","AAKAR DHCP spoofing","AAKAR ARP spoofing","AAKAR STP attack","AAKAR VLAN hopping","AAKAR MAC flooding","AAKAR port security",
        "AAKAR 802.1X bypass","AAKAR EAP vulnerabilities","AAKAR RADIUS security","AAKAR TACACS+ vulnerabilities","AAKAR LDAP security","AAKAR Kerberos vulnerabilities","AAKAR NTLM security","AAKAR OAuth security","AAKAR OpenID vulnerabilities","AAKAR SAML security",
        "AAKAR JWT vulnerabilities","AAKAR session fixation","AAKAR CSRF protection","AAKAR XSS prevention","AAKAR SQL injection","AAKAR XXE vulnerabilities","AAKAR SSRF protection","AAKAR LFI security","AAKAR RFI vulnerabilities",
        "AAKAR RCE prevention","AAKAR deserialization vulnerabilities","AAKAR buffer overflow","AAKAR heap spraying","AAKAR ROP chain","AAKAR ASLR bypass","AAKAR DEP evasion","AAKAR CFG protection","AAKAR sandbox escape","AAKAR VM escape",
        "AAKAR container breakout","AAKAR kernel exploits","AAKAR privilege escalation","AAKAR lateral movement","AAKAR persistence techniques","AAKAR credential dumping","AAKAR pass-the-hash","AAKAR golden ticket","AAKAR silver ticket",
        "AAKAR kerberoasting","AAKAR AS-REP roasting","AAKAR DCSync attack","AAKAR NTLM relay","AAKAR LLMNR poisoning","AAKAR NetBIOS spoofing","AAKAR WPAD attack","AAKAR DNS poisoning","AAKAR DHCP spoofing","AAKAR ARP spoofing","AAKAR STP attack",
        "AAKAR VLAN hopping","AAKAR MAC flooding","AAKAR port security","AAKAR 802.1X bypass","AAKAR EAP vulnerabilities","AAKAR RADIUS security","AAKAR TACACS+ vulnerabilities","AAKAR LDAP security","AAKAR Kerberos vulnerabilities","AAKAR NTLM security",
        "AAKAR OAuth security","AAKAR OpenID vulnerabilities","AAKAR SAML security","AAKAR JWT vulnerabilities","AAKAR session fixation","AAKAR CSRF protection","AAKAR XSS prevention","AAKAR SQL injection","AAKAR XXE vulnerabilities","AAKAR SSRF protection",
        "AAKAR LFI security","AAKAR RFI vulnerabilities","AAKAR RCE prevention","AAKAR deserialization vulnerabilities","AAKAR buffer overflow","AAKAR heap spraying","AAKAR ROP chain","AAKAR ASLR bypass","AAKAR DEP evasion","AAKAR CFG protection",
        "AAKAR sandbox escape","AAKAR VM escape","AAKAR container breakout","AAKAR kernel exploits","AAKAR privilege escalation","AAKAR lateral movement","AAKAR persistence techniques","AAKAR credential dumping","AAKAR pass-the-hash","AAKAR golden ticket",
        "AAKAR silver ticket","AAKAR kerberoasting","AAKAR AS-REP roasting","AAKAR DCSync attack","AAKAR NTLM relay","AAKAR LLMNR poisoning","AAKAR NetBIOS spoofing","AAKAR WPAD attack","AAKAR DNS poisoning","AAKAR DHCP spoofing","AAKAR ARP spoofing",
        "AAKAR STP attack","AAKAR VLAN hopping","AAKAR MAC flooding","AAKAR port security","AAKAR 802.1X bypass","AAKAR EAP vulnerabilities","AAKAR RADIUS security","AAKAR TACACS+ vulnerabilities","AAKAR LDAP security","AAKAR Kerberos vulnerabilities",
        "AAKAR NTLM security","AAKAR OAuth security","AAKAR OpenID vulnerabilities","AAKAR SAML security","AAKAR JWT vulnerabilities","AAKAR session fixation","AAKAR CSRF protection","AAKAR XSS prevention","AAKAR SQL injection",
        "AAKAR XXE vulnerabilities","AAKAR SSRF protection","AAKAR LFI security","AAKAR RFI vulnerabilities","AAKAR RCE prevention","AAKAR deserialization vulnerabilities","AAKAR buffer overflow","AAKAR heap spraying","AAKAR ROP chain",
        "AAKAR ASLR bypass","AAKAR DEP evasion","AAKAR CFG protection","AAKAR sandbox escape","AAKAR VM escape","AAKAR container breakout","AAKAR kernel exploits","AAKAR privilege escalation","AAKAR lateral movement","AAKAR persistence techniques",
        "AAKAR credential dumping","AAKAR pass-the-hash","AAKAR golden ticket","AAKAR silver ticket","AAKAR kerberoasting","AAKAR AS-REP roasting","AAKAR DCSync attack","AAKAR NTLM relay","AAKAR LLMNR poisoning","AAKAR NetBIOS spoofing","AAKAR WPAD attack",
        "AAKAR DNS poisoning","AAKAR DHCP spoofing","AAKAR ARP spoofing","AAKAR STP attack","AAKAR VLAN hopping","AAKAR MAC flooding","AAKAR port security","AAKAR 802.1X bypass","AAKAR EAP vulnerabilities","AAKAR RADIUS security",
        "AAKAR TACACS+ vulnerabilities","AAKAR LDAP security","AAKAR Kerberos vulnerabilities","AAKAR NTLM security","AAKAR OAuth security","AAKAR OpenID vulnerabilities","AAKAR SAML security","AAKAR JWT vulnerabilities","AAKAR session fixation",
        "AAKAR CSRF protection","AAKAR XSS prevention","AAKAR SQL injection","AAKAR XXE vulnerabilities","AAKAR SSRF protection","AAKAR LFI security","AAKAR RFI vulnerabilities","AAKAR RCE prevention",
        "AAKAR deserialization vulnerabilities","AAKAR buffer overflow","AAKAR heap spraying","AAKAR ROP chain","AAKAR ASLR bypass","AAKAR DEP evasion","AAKAR CFG protection","AAKAR sandbox escape","AAKAR VM escape",
        "AAKAR container breakout","AAKAR kernel exploits","AAKAR privilege escalation","AAKAR lateral movement","AAKAR persistence techniques","AAKAR credential dumping","AAKAR pass-the-hash","AAKAR golden ticket",
        "AAKAR silver ticket","AAKAR kerberoasting","AAKAR AS-REP roasting","AAKAR DCSync attack","AAKAR NTLM relay","AAKAR LLMNR poisoning","AAKAR NetBIOS spoofing","AAKAR WPAD attack","AAKAR DNS poisoning",
        "AAKAR DHCP spoofing","AAKAR ARP spoofing","AAKAR STP attack","AAKAR VLAN hopping","AAKAR MAC flooding","AAKAR port security","AAKAR 802.1X bypass","AAKAR EAP vulnerabilities","AAKAR RADIUS security",
        "AAKAR TACACS+ vulnerabilities","AAKAR LDAP security","AAKAR Kerberos vulnerabilities","AAKAR NTLM security","AAKAR OAuth security","AAKAR OpenID vulnerabilities","AAKAR SAML security","AAKAR JWT vulnerabilities",
        "AAKAR session fixation","AAKAR CSRF protection","AAKAR XSS prevention","AAKAR SQL injection","AAKAR XXE vulnerabilities","AAKAR SSRF protection","AAKAR LFI security","AAKAR RFI vulnerabilities",
        "AAKAR RCE prevention","AAKAR deserialization vulnerabilities","AAKAR buffer overflow","AAKAR heap spraying","AAKAR ROP chain","AAKAR ASLR bypass","AAKAR DEP evasion",
    ],
    authors: [{ name: "AAKAR Team", url: "https://aakar2025.in" }],
    creator: "AAKAR Team",
    publisher: "AAKAR Fest Committee",
    robots: "index, follow",
    metadataBase: new URL("https://aakar2025.in"),
    openGraph: {
        title: "AAKAR 2025 | Brains, Guts and Glory",
        description:
            "Join us for AAKAR 2025, the ultimate blend of technology and culture. Participate in events, win prizes, and make unforgettable memories!",
        url: "https://aakar2025.in",
        siteName: "AAKAR 2025",
        images: [
            {
                url: "https://aakar2025.in/Aakarlogo.svg",
                width: 1200,
                height: 630,
                alt: "AAKAR 2025 Banner",
            },
        ],
        locale: "en_US",
        type: "website",
    },
    twitter: {
        card: "summary_large_image",
        title: "AAKAR 2025 | Brains, Guts and Glory",
        description:
            "Tech meets culture at AAKAR 2025! Explore innovation, creativity, and fun at our annual fest.",
        images: ["https://aakar2025.in/Aakarlogo.svg"],
        creator: "@aakar__2025",
    },
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await auth();
    return (
        <html lang="en">
            <head>
                <script async src="https://www.googletagmanager.com/gtag/js?id=G-EXY2XKHRKM"></script>
                <script>
                    {
                        `window.dataLayer = window.dataLayer || [];
                        function gtag(){dataLayer.push(arguments);}
                        gtag('js', new Date());

                        gtag('config', 'G-EXY2XKHRKM');`
                        }
                </script>
            </head>
            <body className={`${GameOfSquids.className} antialiased`}>
                <SessionProvider session={session}>{children}</SessionProvider>
                <Analytics />
                <SpeedInsights />
            </body>
        </html>
    );
}
